<?
//-------------------------------- Initialization --------------------------//
$__in = array();					/**< Global array of input. */
$__out = array();					/**< Global array of output. */
$__config = array();					/**< Global array of configuration automatically generated by the configuration module and saved in uploads/configuration/config.php. */
$__errors = array();					/**< Global array of user errors. */
$__info = array();					/**< Global array of information (any success messages or warnings shown to the user). */
//-------------------------------- DB PROFILES -----------------------------//
$arr_dbprofiles = array();				/**< The array of database profiles. */

$arr_dbprofiles['test']['host'] = "localhost";		/**< Database host. */
$arr_dbprofiles['test']['dbname'] = "fw_db"; 		/**< Database name. */
$arr_dbprofiles['test']['user'] = "root"; 		/**< database user. */
$arr_dbprofiles['test']['pass'] = "";			/**< database password. */
$arr_dbprofiles['test']['dbfile'] = "";			/**< database file for sqlite. */

$arr_dbprofiles['main']['host'] = "localhost";
$arr_dbprofiles['main']['dbname'] = "fw_db";
$arr_dbprofiles['main']['user'] = "root";
$arr_dbprofiles['main']['pass'] = "";
$arr_dbprofiles['main']['dbfile'] = "";

//--------------------------------Language Settings------------------------------------------//
$arr_AVAILABLE_LANGUAGES = array(
"en" => array(
				"name" => "English", 
				"design" => "en"
			 ),
"ar" => array(
                                "name" => "Arabic",
                                "design" => "ar"
                         )
);							/**< The languages available in this site*/
define("DEFAULT_LANGUAGE", "en");			/**< The default language*/
//--------------------------------------------------------------------------//
if ($_SERVER['REMOTE_ADDR'] == "127.0.0.1") { // if the site is accessed from the same machine (on development)
	define("DEBUG", true);				/**< specifies whether the site is in debug mode or not if in debug mode errors are shown on the page else the errors are logged in the log file.*/
} else { // if the site is accessed from other IP
	define("DEBUG", true);
}
define("ENABLE_POST_REPITITION_STOPPER", true);		/**< Enable Post Repitition stopper on production code */

define("DEFAULT_DBPROFILE", "test");			/**< the database profile with which the web site will connect to its database. */
define("HTML_ROOT", "/trunk/");				/**< the HTML root of the site set to / if the site is on the document root or set to another folder if it is on a sub folder. used by the browser to access images or style sheets on the site. */

define("ENABLE_FRIENDLY_URLS", true);			/**< enable friendly_urls */
define("ENABLE_REWRITE_URL", true);			/**< Is Rewrite Engine Enabled */
define("ENABLE_JSON_GATEWAY", true);			/**< enable the JSON gateway true|false. */
define("ENABLE_XML_GATEWAY", false);			/**< enable the XML gateway true|false. */

define("DB_ENGINE", "mysql");				/**< The database engine select from these (mysqk, sqlite)*/
define("SESSION_METHOD", "db_session");			/**< can be any of the following [ db_session | php_session | file_session | cookie_session] */
define("SESSION_TIMEOUT", 1800);			/**< The session timeout in seconds used only if you are using db or file session */
define("DEFAULT_THEME", "default");			/**< the default theme of this site. */

define("PHP_ROOT", dirname(__FILE__) . "/");		/**< the PHP root of the application it is the Server document root variable + the html root (used by php to access files on the site.) */
define('SMARTY_DIR', PHP_ROOT . 'smarty/libs/');	/**< The smarty directory constrant used by the smarty classes*/

define("INTERNAL_ERRORMSG", "<h1>Internal Server Error.</h1><h3>Please try again later.</h3>");		/**< A message shown to the user if an internal error happened and DEBUG=false. **/

// SMTP Mail Settings
define("SMTP_SERVER", "ssl://smtp.gmail.com");
define("SMTP_USERNAME", "username@gmail.com");
define("SMTP_PASSWORD", "123456");


$__out['DEBUG'] = DEBUG;
$__out['HTML_ROOT'] = HTML_ROOT;
$__out['FRAMEWORK_VERSION'] = "1.2.0";
$__out['APPLICATION_VERSION'] = "1.0.0";
$__out['__page_title'] = "Frame Work " . $__out['FRAMEWORK_VERSION'];
$__out['DOMAIN'] = "localhost";
