<?
/**
@author Ahmed Magdy Ezzeldin <admin@a1works.com>
Fills an array with numbers generated by a for loop.
@param assign required
@param start
@param max required
@param step
*/
function smarty_function_for ($params, &$smarty) {
	if (!$params['assign']) return "";
	if (!$params['start']) $params['start'] = 0;
	if (!$params['step']) $params['step'] = 1;
	$arr = array();
	for ($i=$params['start']; $i<=$params['max']; $i=$i+$params['step']) {
		$arr[] = $i;
	}	
	$smarty->assign($params['assign'], $arr);
	return "";
}

